CREATE TABLE books(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  publish_date DATE,
  archived BOOLEAN,
  publisher VARCHAR(255),
  cover_state VARCHAR(255),
);

CREATE TABLE labels(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  title VARCHAR(255),
  color VARCHAR(255),
  FOREIGN KEY(item_id) REFERENCES items(id)
);

CREATE TABLE MusicAlbum(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  on_spotify BOOLEAN,
  publish_date DATE
);

CREATE TABLE genre(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  name VARCHAR(255),
  FOREIGN KEY(item_id) REFERENCES items(id)
);

CREATE TABLE game (
    id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
    last_played_date DATE NOT NULL,
    multiplayer BOOLEAN NOT NULL,
    FOREIGN KEY(item_id) REFERENCES items(id)
);

CREATE TABLE author (
    id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);

